---
    version: '3.7'
    services:
        zegami_sdk:
            build:
                context: ./
                dockerfile: Dockerfile
            image: zegami/zegami-python-sdk
            init: true
            volumes:
                - ./:/app/
            environment:
                DEBUG: 'True'
                PYTHONPATH: /app
                PYTHONUNBUFFERED: 1  # Ensure Python logs to stdout without delay
                ZEGAMI_SDK_VERSION: ${ZEGAMI_SDK_VERSION}
                SDK_PRODUCTION_BUILD: ${SDK_PRODUCTION_BUILD}
            command:
                - bash
